### ISSUE TITLE
Debug.css file styles  in framework are leaching into the CMS UI

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/bambusa-theme#21]
I've noticed the styles are coming through from the debug.css file in Framework to the Site tree and block header, there are likely to be other styles as well. This problem doesn't seem to be occurring with other projects outside of Bambusa from what I can tell.

<img width="540" alt="Pasted_Image_24_07_19__10_19_AM" src="https://user-images.githubusercontent.com/555033/61755683-cafe1300-ae0c-11e9-9474-4679325e4a4f.png">

# Pull requests
* [x] https://github.com/silverstripe/bambusa-installer/pull/49

**Comment by chillu** [comment]
Another screenshot of headline comparisons - standard 4.x on the left, bambusa on the right

![image](https://user-images.githubusercontent.com/111025/61824548-64cbcb80-aeb2-11e9-9f47-b6f1ab08cd61.png)

**Comment by maxime-rainville** [comment]
I figured out what the problem is with that debug.css. It's a bug with the vulcan seo module. It tries to render the page using the correct page controller. However because it's doing that in the left'n'main context it can't find any of the matching templates from the theme. This leads it to render the page using our bare bones controller template which include the debug.css file from template. This causes the debug.css to be included in the imports of the current request.

This has the added downside that the Search Preview doesn't work for block pages which sounds like a big problem.

The best solution is probably to switch to a different SEO module. Need to confirm with @chillu.

**Comment by chillu** [comment]
We've removed the SEO module, which fixes this issue
